//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lips.Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lips.Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;xml&quot; encoding=&quot;utf-8&quot; indent=&quot;no&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///     &lt;xsl:variable name=&quot;dt&quot; select=&quot;UserDto/Guid&quot;/&gt;
        ///      &lt;xsl:variable name=&quot;data&quot; select=&quot;UserDto/BirthDate&quot;/&gt;
        ///  
        ///    &lt;html&gt;
        ///      &lt;body style=&quot;width:700px;&quot;&gt;
        ///        &lt;p&gt;
        ///          Geachte  &lt;xsl:value-of select=&quot;UserDto/Name&quot;/&gt;
        ///        &lt;/p&gt;
        ///
        ///        &lt;p&gt;
        ///          Bedankt voor uw aanvraa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ActivateNewUser {
            get {
                return ResourceManager.GetString("ActivateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;xml&quot; encoding=&quot;utf-8&quot; indent=&quot;no&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;body&gt;
        ///        &lt;p&gt;
        ///          Geachte  &lt;xsl:value-of select=&quot;ContactRequestObject/Name&quot;/&gt;
        ///        &lt;/p&gt;
        ///
        ///        &lt;p&gt;
        ///          Bedankt voor uw informatie aanvraag over onze dienstverlening.
        ///          &lt;br/&gt; Hieronder staan de gegevens zoals wij die van u hebben ontvangen.
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContactRequestClient {
            get {
                return ResourceManager.GetString("ContactRequestClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;xml&quot; encoding=&quot;utf-8&quot; indent=&quot;no&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;body&gt;
        ///      
        ///
        ///        &lt;p&gt;
        ///          Svp contact opnemen met:
        ///        &lt;/p&gt;
        ///        &lt;table border=&quot;0&quot; width=&quot;500px&quot;&gt;
        ///          &lt;colgroup&gt;
        ///            &lt;col style=&quot;width: 25%&quot;/&gt;
        ///            &lt;col style=&quot;width: 75&quot;/&gt;
        ///          &lt;/colgroup&gt;
        ///         
        ///          &lt;tr&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContactRequestLips {
            get {
                return ResourceManager.GetString("ContactRequestLips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;xml&quot; encoding=&quot;utf-8&quot; indent=&quot;no&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;xsl:variable name=&quot;dt&quot; select=&quot;UserDto/Guid&quot;/&gt;
        ///    &lt;xsl:variable name=&quot;data&quot; select=&quot;UserDto/BirthDate&quot;/&gt;
        ///
        ///    &lt;html&gt;
        ///      &lt;body&gt;
        ///
        ///        &lt;p&gt;
        ///          Volgende gegevens svp verwerken en tezamen met de QR code mailen naar de aanvrager:
        ///         
        ///        &lt;/p&gt;
        ///        &lt;table border=&quot;0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewQRCodeLips {
            get {
                return ResourceManager.GetString("NewQRCodeLips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;xml&quot; encoding=&quot;utf-8&quot; indent=&quot;no&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///     &lt;xsl:variable name=&quot;dt&quot; select=&quot;UserDto/Guid&quot;/&gt;
        ///      &lt;xsl:variable name=&quot;data&quot; select=&quot;UserDto/BirthDate&quot;/&gt;
        ///  
        ///    &lt;html&gt;
        ///      &lt;body&gt;
        ///        &lt;p&gt;
        ///          Geachte  &lt;xsl:value-of select=&quot;UserDto/Name&quot;/&gt;
        ///        &lt;/p&gt;
        ///
        ///        &lt;p&gt;
        ///          Bedankt voor uw aanvraag voor een QR code om [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewQRCodeLipsClient {
            get {
                return ResourceManager.GetString("NewQRCodeLipsClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;xml&quot; encoding=&quot;utf-8&quot; indent=&quot;no&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;body&gt;
        ///        &lt;p&gt;
        ///          Geachte  &lt;xsl:value-of select=&quot;RegisterUserDto/Name&quot;/&gt;
        ///        &lt;/p&gt;
        ///
        ///        &lt;p&gt;
        ///          Hartelijk dank voor uw betaling aan LIPS+.
        ///          Deze mail sturen wij als ontvangstbevestiging voor een bedrag van &lt;xsl:value-of select=&quot;RegisterUserDt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentLastStatusClient {
            get {
                return ResourceManager.GetString("PaymentLastStatusClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;xml&quot; encoding=&quot;utf-8&quot; indent=&quot;no&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;xsl:variable name=&quot;dt&quot; select=&quot;RegisterUserDto/DateOfBirth&quot;/&gt;
        ///    &lt;html&gt;
        ///      &lt;body&gt;
        ///        &lt;p&gt;
        ///          Geachte  &lt;xsl:value-of select=&quot;RegisterUserDto/Name&quot;/&gt;
        ///      &lt;/p&gt;
        ///       
        ///        &lt;p&gt;
        ///          Bedankt voor het afgeven van een machtiging tot automatische afschrijving van de wa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentNewClient {
            get {
                return ResourceManager.GetString("PaymentNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;xml&quot; encoding=&quot;utf-8&quot; indent=&quot;no&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;xsl:variable name=&quot;md&quot; select=&quot;RegisterUserDto/ModifiedDate&quot;/&gt;
        ///    &lt;xsl:variable name=&quot;dt&quot; select=&quot;RegisterUserDto/DateOfBirth&quot;/&gt;
        ///
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;style&gt;
        ///          table {
        ///          font-family: arial, sans-serif;
        ///          border-collapse: collapse;
        ///          width: 7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentNewClientLips {
            get {
                return ResourceManager.GetString("PaymentNewClientLips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;xml&quot; encoding=&quot;utf-8&quot; indent=&quot;no&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt; 
        ///    &lt;html&gt;
        ///      &lt;body&gt;
        ///        &lt;p&gt;
        ///          Geachte  &lt;xsl:value-of select=&quot;RegisterUserDto/Name&quot;/&gt;
        ///        &lt;/p&gt;
        ///
        ///        &lt;p&gt;
        ///          Wij zijn in afwachting van uw betaling.
        ///          &lt;br/&gt;Zodra deze is ontvangen zullen wij u ontvangstbevestiging sturen.
        ///        &lt;/p&gt;
        /// 
        ///        &lt;p&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentPendingClient {
            get {
                return ResourceManager.GetString("PaymentPendingClient", resourceCulture);
            }
        }
    }
}
